interface Env {
  ALERT_WEBHOOK_ENABLED?: string;
  ALERT_WEBHOOK_TOKEN?: string;
  ALERT_WEBHOOK_ALERT_NAMES?: string;
  ALERT_WEBHOOK_AGENT_NAME?: string;
  ALERT_INVESTIGATION_SINCE_SECONDS?: string;
  TOOL_API_BASE_URL: string;
  TOOL_API_TOKEN: string;
  MODEL_PROVIDER: string;
  GEMINI_AI_MODEL: string;
  CLOUDFLARE_AI_MODEL: string;
  OPENROUTER_AI_MODEL: string;
  OPENROUTER_API_KEY: string;
  OPENROUTER_BASE_URL: string;
  EMBEDDING_PROVIDER: string;
  GEMINI_EMBEDDING_MODEL: string;
  CLOUDFLARE_EMBEDDING_MODEL: string;
  EMBEDDING_DIMENSIONS: string;
  INCIDENT_MEMORY_NAMESPACE: string;
  GOOGLE_GENERATIVE_AI_API_KEY: string;
  AI_GATEWAY_BASE_URL?: string;
  AI_GATEWAY_TOKEN?: string;
}
