interface Env {
  TOOL_API_BASE_URL: string;
  TOOL_API_TOKEN: string;
  MODEL_PROVIDER: string;
  GEMINI_AI_MODEL: string;
  CLOUDFLARE_AI_MODEL: string;
  EMBEDDING_PROVIDER: string;
  GEMINI_EMBEDDING_MODEL: string;
  CLOUDFLARE_EMBEDDING_MODEL: string;
  EMBEDDING_DIMENSIONS: string;
  INCIDENT_MEMORY_NAMESPACE: string;
  GOOGLE_GENERATIVE_AI_API_KEY: string;
  AI_GATEWAY_BASE_URL?: string;
  AI_GATEWAY_TOKEN?: string;
}
